<img src="img1.jpeg">

<img src="img2.jpeg">

In [ ]:
import numpy as np

# AI GENRATED CODE TO VERIFY THE RESULTS ABOVE !!!!!!!!!!!!!!
# --- Étape 1 : Initialisation des données ---
# Définition des embeddings pour "The cat sat" (taille = 4)
E_the = np.array([1, 0, 1, 0])
E_cat = np.array([0, 1, 0, 1])
E_sat = np.array([1, 1, 1, 1])

# Regroupement dans une matrice X (shape: 3 mots x 4 dimensions)
X = np.array([E_the, E_cat, E_sat])

# Matrices de poids : Matrice Identité (taille 4x4)
W_Q = np.eye(4)
W_K = np.eye(4)
W_V = np.eye(4)

print("--- 1. MATRICES DE DÉPART (X) ---")
print(f"X (The) : {X[0]}")
print(f"X (Cat) : {X[1]}")
print(f"X (Sat) : {X[2]}\n")


# --- Étape 2 : Calcul de Q, K, V ---
# Comme W est l'identité, Q, K, V seront égaux à X
Q = np.dot(X, W_Q)
K = np.dot(X, W_K)
V = np.dot(X, W_V)

print("--- 2. VECTEURS Q, K, V POUR CHAQUE MOT ---")
mots = ["The", "Cat", "Sat"]
for i, mot in enumerate(mots):
    print(f"Q_{mot.lower()} : {Q[i]}")
    print(f"K_{mot.lower()} : {K[i]}")
    print(f"V_{mot.lower()} : {V[i]}")
    print("-" * 20)
print()


# --- Étape 3 : Attention Scores (Q * K^T) ---
# Produit matriciel entre Q et la transposée de K
scores_bruts = np.dot(Q, K.T)

print("--- 3. ATTENTION SCORES BRUTS (Q * K^T) ---")
print("Matrice des 9 scores (Lignes = Query, Colonnes = Key) :")
print(scores_bruts)
print("\nDétail des 9 calculs manuels (produits scalaires) :")
for i in range(3):
    for j in range(3):
        print(
            f"Score(Q_{mots[i].lower()}, K_{mots[j].lower()}) = {Q[i]} • {K[j]} = {scores_bruts[i, j]}"
        )
print()


# --- Étape 4 : Scaling (Division par sqrt(d_k)) ---
d_k = 4
sqrt_dk = np.sqrt(d_k)  # égale à 2.0
scores_scaled = scores_bruts / sqrt_dk

print(f"--- 4. SCORES APRÈS SCALING (Divisé par sqrt({d_k}) = {sqrt_dk}) ---")
print("Matrice des 9 scores mis à l'échelle :")
print(scores_scaled)
print("\nDétail des 9 valeurs :")
for i in range(3):
    for j in range(3):
        print(
            f"Scaled_Score({mots[i].lower()}, {mots[j].lower()}) = {scores_bruts[i, j]} / {sqrt_dk} = {scores_scaled[i, j]}"
        )
print()


# --- Étape 5 : Softmax ---
def softmax(matrix):
    # Applique le softmax sur chaque ligne de la matrice
    exp_matrix = np.exp(matrix)
    sum_per_row = np.sum(exp_matrix, axis=1, keepdims=True)
    return exp_matrix / sum_per_row, exp_matrix, sum_per_row


matrice_attention, exps, sommes = softmax(scores_scaled)

print("--- 5. APPLICATION DU SOFTMAX ---")
print("Pour tes calculs à la main, voici les exponentielles e^x des 9 valeurs :")
print(exps)
print("\nSomme des exponentielles pour chaque ligne (le dénominateur) :")
for i, mot in enumerate(mots):
    print(f"Somme ligne {mot} : {sommes[i][0]}")

print("\nMatrice d'Attention finale (les 9 pourcentages) :")
print(matrice_attention)
print("\nDétail des 9 poids d'attention :")
for i in range(3):
    for j in range(3):
        print(
            f"Poids({mots[i].lower()} -> {mots[j].lower()}) = e^{scores_scaled[i, j]:.2f} / {sommes[i][0]:.4f} = {matrice_attention[i, j]:.4f}"
        )
print()


# --- Étape 6 : Somme pondérée des valeurs (Attention * V) ---
# Produit matriciel final entre la matrice d'attention et V
O = np.dot(matrice_attention, V)

print("--- 6. SOMME PONDÉRÉE DES VALEURS (RÉSULTAT FINAL) ---")
print("Matrice de sortie finale (3 mots x 4 dimensions) :")
print(O)
print("\nDétail du calcul pour chaque mot :")
for i in range(3):
    print(f"\n[Nouveau vecteur pour '{mots[i]}'] :")
    print(
        f"  = {matrice_attention[i, 0]:.4f} * V_the + {matrice_attention[i, 1]:.4f} * V_cat + {matrice_attention[i, 2]:.4f} * V_sat"
    )
    print(
        f"  = {matrice_attention[i, 0]:.4f}*{V[0]} + {matrice_attention[i, 1]:.4f}*{V[1]} + {matrice_attention[i, 2]:.4f}*{V[2]}"
    )
    print(f"  = {O[i]}")

--- 1. MATRICES DE DÉPART (X) ---
X (The) : [1 0 1 0]
X (Cat) : [0 1 0 1]
X (Sat) : [1 1 1 1]

--- 2. VECTEURS Q, K, V POUR CHAQUE MOT ---
Q_the : [1. 0. 1. 0.]
K_the : [1. 0. 1. 0.]
V_the : [1. 0. 1. 0.]
--------------------
Q_cat : [0. 1. 0. 1.]
K_cat : [0. 1. 0. 1.]
V_cat : [0. 1. 0. 1.]
--------------------
Q_sat : [1. 1. 1. 1.]
K_sat : [1. 1. 1. 1.]
V_sat : [1. 1. 1. 1.]
--------------------

--- 3. ATTENTION SCORES BRUTS (Q * K^T) ---
Matrice des 9 scores (Lignes = Query, Colonnes = Key) :
[[2. 0. 2.]
 [0. 2. 2.]
 [2. 2. 4.]]

Détail des 9 calculs manuels (produits scalaires) :
Score(Q_the, K_the) = [1. 0. 1. 0.] • [1. 0. 1. 0.] = 2.0
Score(Q_the, K_cat) = [1. 0. 1. 0.] • [0. 1. 0. 1.] = 0.0
Score(Q_the, K_sat) = [1. 0. 1. 0.] • [1. 1. 1. 1.] = 2.0
Score(Q_cat, K_the) = [0. 1. 0. 1.] • [1. 0. 1. 0.] = 0.0
Score(Q_cat, K_cat) = [0. 1. 0. 1.] • [0. 1. 0. 1.] = 2.0
Score(Q_cat, K_sat) = [0. 1. 0. 1.] • [1. 1. 1. 1.] = 2.0
Score(Q_sat, K_the) = [1. 1. 1. 1.] • [1. 0. 1. 0.] = 2.0
Sco